---
title: "Homework 6"
author: Sarah McLarnan
date: 2019-11-19
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

### Problem 1

```{r read and tidy}
birthweight = read_csv("./data/birthweight.csv")

birthweight = 
  birthweight %>%
  drop_na() %>%
  mutate(
    babysex = factor(babysex),
    babysex = recode(babysex, "1" = "male", "2" = "female"),
    frace = factor (frace),
    frace = recode(frace, "1" = "white", "2" = "black", "3" = "asian", "4" = "puerto rican", "8" = "other", "9" = "unkown"),
    malform = factor(malform), 
    malform = recode(malform, "0" = "absent", "1" = "present"),
    mrace = factor(mrace), 
    mrace = recode(mrace, "1" = "white", "2" = "black", "3" = "asian", "4" = "puerto rican", "8" = "other")
  )
```

```{r model building}
bw_model = lm(bwt ~ gaweeks + blength + fincome + wtgain, data = birthweight)

birthweight %>%
  add_residuals(bw_model) %>%
  add_predictions(bw_model) %>%
  ggplot(aes(x = pred, y = resid)) +
          geom_point() +
          labs (x = "Prediction", y = "Residual", title = "Residuals by Prediction of Proposed Birthweight Model")

comp_model1 = lm(bwt ~ gaweeks + blength, data = birthweight)
comp_model2 = lm(bwt ~ babysex * blength * bhead, data = birthweight)
```

```{r Cross Validation}
cv_df = 
  crossv_mc(birthweight, 100)

cv_df = cv_df %>% 
  mutate(bw_model  = map(train, ~lm(bwt ~ gaweeks + blength + fincome + wtgain, data = .x)),
         comp_model1  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         comp_model2  = map(train, ~lm(bwt ~ bhead + blength + babysex +  bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_1 = map2_dbl(bw_model, test, ~modelr::rmse(model = .x, data = .y)),
         rmse_2 = map2_dbl(comp_model1, test, ~modelr::rmse(model = .x, data = .y)),
         rmse_3 = map2_dbl(comp_model2, test, ~modelr::rmse(model = .x, data = .y)))

cv_plot = cv_df %>% 
  select(starts_with("rmse")) %>% 
pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
cv_plot 
```





